version: '3.3'
services:
  rabbitmq:
    image: rabbitmq
    env_file:
      - .env
    ports:
      - "21001:5672"
      - "21002:15672"
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "21003:5432"
  web:
    build: .
    restart: always
    command: bash -c "
        python manage.py migrate --noinput &&
        python manage.py createsuperuser --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
  queue-default:
    build: .
    restart: always
    command: celery -A django_celery.celery_app:app  worker -Q default -n tasks.%%h --without-gossip --without-mingle --without-heartbeat --loglevel=INFO --max-memory-per-child=512000 --concurrency=1
    env_file:
      - .env
    volumes:
      - .:/code
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
