version: '3.3'
services:
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_DEFAULT_VHOST=queue
    ports:
      - "21001:5672"
      - "21002:15672"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
  queue-default:
    build: .
    restart: always
    command: celery -A django_celery.celery_app:app  worker -Q default -n tasks.%%h --without-gossip --without-mingle --without-heartbeat --loglevel=INFO --max-memory-per-child=512000 --concurrency=1
    env_file:
      - .env
    volumes:
      - .:/code
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
