# Generated by Django 4.1.7 on 2023-03-30 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 12, 47, 15, 538741)),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
